load hw2_data;
n = size (A1,1);
figure(1), clf ;
subplot(2,2,1), imshow(reshape(b1,n,n),[]);
title ('b_1 Data');
subplot(2,2,2), imshow(reshape(b2,n,n),[]);
title ('b_2 Data');
x_KronLS = KronLS(A1,A2,b1,b2);
subplot(2,1,2), imshow(reshape(x_KronLS,n,n),[]);
title ('LS Solution');
